### ISSUE TITLE
xdebug dll from wizard tagged as potentially dangerous by browser

### ISSUE THREAD

**Issue by jovelluna12** [xdebug/xdebug.org#133]
the xdebug dll file that the wizard told me to download is tagged as potentially dangerous by the browser. While there is an option to download this file regardless, the fact that it was said to be dangerous got me scared. 

Is this even safe at all ? 

![image](https://github.com/user-attachments/assets/860d3ee1-d84f-43a0-bfc7-8b676bd5d907)

![image](https://github.com/user-attachments/assets/cba79dfc-0292-4503-8f83-cd4a57d77899)

**Comment by derickr** [comment]
It's a warning from Chrome. You'll have to ask them why they do this (they do include a "Learn why Chrome blocks some downloads" as you can see in their screenshot).

In the end, you are downloading a binary from a source that you might or might not trust. In order to alleviate that trust, you can download the source, inspect and read all of it, and then make your own binary, but I am going to guess that's too much work for you, and most other people.

However, in this case you could trust me that this binary is made from the GIT tag on GitHub. You can verify that at least the binary hasn't changed since I created it, by comparing with the SHA256 sum that I published against your downloaded file (https://github.com/xdebug/xdebug.org/commit/8c22033824142162423b637dbcc635d18d98f39b#diff-38418bcbd2a943229b1c1480a3d21a59d00a866c4ba3150031a9227e750ff39f).

From Xdebug 3.3.1 onwards, all these files are automatically made on GitHub with their actions, which should provide you the trust that these binaries haven't been tampered with (https://github.com/xdebug/xdebug/releases).
