### ISSUE TITLE
xdebug.org Website down

### ISSUE THREAD

**Issue by luckydonald** [xdebug/xdebug.org#49]
[![image](https://user-images.githubusercontent.com/2737108/47559484-eab3e980-d915-11e8-8eda-4038737e2c05.png)](http://www.isitdownrightnow.com/xdebug.org.html)

**Comment by derickr** [comment]
This should be fixed now. I had upgraded my system and libraries, which then broke the PHP CGI as it was linked to a version of OpenSSL that was no longer on the system. Upgrading to PHP 7.2.11 fixed that problem, but then because OpenSSL is now 1.1.1, it triggered the following bug in lighttpd: https://redmine.lighttpd.net/issues/2912, which I've now worked around.

**Comment by lezhnev74** [comment]
Hey! Just found out that the website is not available. I bet you have your monitoring in place.
